version: "2"
services:
  wpt_server:
    volumes:
      - ./wpt-server/settings/locations-macos.ini:/var/www/html/settings/locations.ini
  wpt_agent:
    environment:
      LOCATION: MacOS
      SHAPER: none
